name: car-rest-service

services:
    api:
        image: car-service
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db_pg
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db_pg:5432/cars_db
        container_name: "api-car-service"

    db_pg:
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_DB: cars_db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1111
        ports:
            - "5433:5432"
        container_name: "db-pg"

    keycloak:
        image: quay.io/keycloak/keycloak:25.0.1
        restart: always
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
            - "8888:8080"
        volumes:
            - './config/keycloak:/opt/keycloak/data'
        depends_on:
            - db_pg
        command: start-dev
        container_name: "keycloak"