spring:
    application:
        name: CarRestService

    profiles:
        active: default

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/cars_db
        username: admin
        password: 1111


    flyway:
        locations: db/migration
        schemas:
            - public
            - car
        enabled: true

    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    batch_size: 100
                order_updates: true
                order_inserts: true